{{- include "ars.validate" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ars.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ars.labels" . | nindent 4 }}
data:
  ARS_SINK_ADDR: {{ printf ":%v" .Values.containerPorts.sink | quote }}
  ARS_OPS_ADDR: {{ printf ":%v" .Values.containerPorts.ops | quote }}
  ARS_HOSTS: {{ join "," .Values.interception.hosts | quote }}
  ARS_PROFILES: {{ join "," .Values.profiles | quote }}
  ARS_TOAST_ENABLED: {{ .Values.toast.enabled | toString | quote }}
  ARS_TOAST_DETAILS: {{ .Values.toast.details | toString | quote }}
  ARS_METRICS_SITES_ENABLED: {{ .Values.metrics.sites.enabled | toString | quote }}
  ARS_METRICS_SITES_MAX: {{ .Values.metrics.sites.max | toString | quote }}
  ARS_METRICS_UPSTREAMS_MAX: {{ .Values.metrics.upstreams.max | toString | quote }}
  ARS_LOG_LEVEL: {{ .Values.logLevel | quote }}
  ARS_LOG_FORMAT: {{ .Values.logFormat | quote }}
  {{- with .Values.hostname }}
  ARS_HOSTNAME: {{ . | quote }}
  {{- end }}
