{{- include "ars.validate" . -}}
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ars.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ars.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ars.selectorLabels" . | nindent 6 }}
{{- end }}
